name: Build Release App Bundle

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          echo "Checking current directory permissions:"
          ls -l
          
          echo "Testing write permissions:"
          touch testfile && echo "Write permissions are available" || echo "Write permissions are not available"
          rm testfile

          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          echo "TMP_KEYSTORE_FILE_PATH is set to ${TMP_KEYSTORE_FILE_PATH}"
          mkdir -p "${TMP_KEYSTORE_FILE_PATH}"
          echo "Contents of TMP_KEYSTORE_FILE_PATH directory:"
          ls -la "${TMP_KEYSTORE_FILE_PATH}"

          KEYPATH="${TMP_KEYSTORE_FILE_PATH}/upload-keystore.jks"
          echo "KEYPATH is set to ${KEYPATH}"
          echo $ENCODED_STRING | base64 -di > "${KEYPATH}"
          echo "Keystore file contents:"
          
          echo "Contents of the directory where the keystore should be:"
          ls -la "${TMP_KEYSTORE_FILE_PATH}"

          if [ -f "$KEYPATH" ]; then
          echo "Keystore file exists at $KEYPATH"
          else
          echo "Keystore file does not exist at $KEYPATH"
          fi

      - name: List files in the directory
        run: ls ${TMP_KEYSTORE_FILE_PATH}
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build prod
        run: ./gradlew app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/