name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Send APK to email
        env:
          APK_FILE: app/build/outputs/apk/debug/app-debug.apk
          EMAIL: vptarasov1998@gmail.com
          PASSWORD: Tarasov*2022
        run: |
          echo "Sending APK file to ${EMAIL}"
          echo "Subject: New APK build" | cat - ${APK_FILE} | ssmtp -au "${EMAIL}" -ap 
