name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Run Lint
      run: ./gradlew lintDebug

    - name: Run tests with Gradle
      run: ./gradlew test

    - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.2.0
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_AUTH }}
          project_id: smart-blocker-369210

    - name: Install gcloud
        run: |
          export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
          echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update && sudo apt-get install google-cloud-sdk
          
    - name: Run tests on Firebase Test Lab
      run: |
        gcloud firebase test android run \
        --type instrumentation \
        --app app/build/outputs/apk/debug/app-debug.apk \
        --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
        --device-ids NexusLowRes \
        --timeout 5m

      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_AUTH }}
        
        


