name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  assemble_ui_test_artifacts:
    name: Build artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 1.11 }

      - name: Build and test
        run: |
          ./gradlew clean build connectedCheck

      - name: Generate JaCoCo Reports
        run: |
          ./gradlew jacocoTestReport jacocoAndroidTestReport

      - name: Upload reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/jacoco