name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  env:
    APK_FILE: app/build/outputs/apk/debug/app-debug.apk
    EMAIL: vptarasov1998@gmail.com
    PASSWORD: Tarasov*2022