name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  assemble_ui_test_artifacts:
    name: Build artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 1.11 }

      - name: Convert Test Coverage Report to XML
        run: |
          ./gradlew jacocoTestReport

      - name: Find jacoco-report.xml
        run: |
          echo "The workspace directory is $GITHUB_WORKSPACE"
          find $GITHUB_WORKSPACE -name "jacoco-report.xml" -type f

      - name: Commit and Push Test Coverage Report
        run: |
          git config --global user.name "TarasovVP"
          git config --global user.email "vptarasov1998@gmail.com"
          git checkout -b test-coverage-report
          cp /home/runner/work/SmartBlocker/SmartBlocker/jacoco-report.xml -type f) ./coverage-report.xml
          git add coverage-report.xml
          git commit -m "Update test coverage report"
          git push origin test-coverage-report