package com.tarasovvp.blacklister.constants

object Constants {

    const val REALTIME_DATABASE =
        "https://blacklister-b6048-default-rtdb.europe-west1.firebasedatabase.app"
    const val SERVER_CLIENT_ID = "576475361826-qqu63i7ii3aquesphf7e071osjjh6178.apps.googleusercontent.com"
    const val USERS = "users"
    const val PHONE_NUMBER_CODE = "+380"
    const val THREE_EIGHT_ZERO = "380"
    const val EIGHT_ZERO = "80"
    const val ZERO = "0"
    const val BLACK_NUMBER = "blackNumber"
    const val WHITE_NUMBER = "whiteNumber"
    const val WHITE_LIST_PRIORITY = "whiteListPriority"
    const val BLACK_LIST = "blackList"
    const val WHITE_LIST = "whiteList"
    const val DELETE_NUMBER = "addNumber"
    const val CONTACT = "contact"
    const val CALL_LOG_CALL = "content://call_log/calls"
    const val GET_IT_TELEPHONY = "getITelephony"
    const val END_CALL = "endCall"
    const val OUTCOMING_CALL = "2"
    const val MISSED_CALL = "3"
    const val REJECTED_CALL = "5"
    const val BLOCKED_CALL = "6"
    const val TIME_FORMAT = "HH:mm:ss"
    const val DATE_FORMAT = "dd.MM.yyyy"
    const val NOTIFICATION_CHANNEL = "NOTIFICATION_CHANNEL"
    const val FOREGROUND_CALL_SERVICE = "foregroundCallService"
    const val FOREGROUND_ID = 99
    const val PHONE_STATE = "android.intent.action.PHONE_STATE"
    const val DESC = "DESC"
    const val NUMBER = "NUMBER="
    const val DATE = "DATE="
    const val TYPE = "TYPE="
    const val ACCEPT_PERMISSIONS_SCREEN = 3
    const val CALL_RECEIVE = "callReceive"
    const val APP_EXIT = "appExit"
    const val APP_LANG_RU = "ru"
    const val APP_LANG_UA = "ua"
    const val APP_LANG_EN = "en"
    const val FORGOT_PASSWORD = "forgotPassword"
    const val DELETE_USER = "deleteUser"
    const val LOG_OUT = "logOut"
}